### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by daT7F4** [carlos-menezes/gran-turismo-query#1]
How am i supposed to get it to run?
I am using a linux computer but i can't figure out how to get it to run

**Comment by daT7F4** [comment]
i just get this error

error: expected item, found keyword `let`
 --> src/main.rs:2:1
  |
2 | let socket = UdpSocket::bind("0.0.0.0:33740").expect("Failed to bind socket");
  | ^^^ consider using `const` or `static` instead of `let` for global variables

error: could not compile `gran-turismo-query` (bin "gran-turismo-query") due to 1 previous error

**Comment by carlos-menezes** [comment]
@daT7F4 Take the code from the example and put it inside the main function. You should then be able to compile.

**Comment by daT7F4** [comment]
Now I get errors about Packet variables(like PACKET_HEARTBEAT_DATA) and the UdpSocket and SocketAddr

**Comment by carlos-menezes** [comment]
You are not importing them from `gran-turismo-query`.

**Comment by daT7F4** [comment]
Ok, it compiles without errors now, but even with the playstation off it doesn't say "Invalid IP Adress or Port". Do I need some special permissions for it to work?

**Comment by carlos-menezes** [comment]
> Ok, it compiles without errors now, but even with the playstation off it doesn't say "Invalid IP Adress or Port". Do I need some special permissions for it to work?

The "Invalid IP address or port" error only occurs if you pass in an invalid `SocketAddr` (e.g. `192.168.1.1.1:59999`). If your PlayStation is on and the address is valid, you should be able to receive the packets.

**Comment by daT7F4** [comment]
Tried that and it didn't work, btw, I'm using a PS4 and GTS, I suppose it doesn't work for that

**Comment by carlos-menezes** [comment]
This doesn't offer support for GTS, only GT7. It should be fairly easy to add support to GTS, but I do not own a PS4 nor GTS, and thus I cannot test the implementation.

**Comment by daT7F4** [comment]
I do, I could give some debug data for you if you want

**Comment by daT7F4** [comment]
I just need some code to run
